### ISSUE TITLE
Where is "Factorizable Net" in the code?

### ISSUE THREAD

**Issue by seungjun45** [he-dhamo/simsg#1]
Hello,

Thank you for providing the valuable code publicly available.
Currently, I am following up on the code, but I could not find "Scene Graph Predictor."
It seems like the code in here uses Ground-Truth Scene-Graph (provided by VisualGenome site) triplets, not from the "Factorizable Net."
Is it correct?

**Comment by azadef** [comment]
We have both variations, one using the ground truth scene graphs and one using the graphs predicted by Factorizable Net. We have not included the code for the predictor, but we have used the implementation from this repository trained on our VG subset: https://github.com/yikang-li/FactorizableNet

**Comment by he-dhamo** [comment]
By the way, we have updated the webpage with the download link to predicted graphs from factorizable net:

https://he-dhamo.github.io/SIMSG/#download

________________________________

**Comment by seungjun45** [comment]
Thank youuuuuu :)
