### ISSUE TITLE
*** KeyError: 'decoder_net.decoder_modules.0.conv_0.weight'

### ISSUE THREAD

**Issue by wang-zm18** [he-dhamo/simsg#12]
When I tried to load the pre-trained "spade_64_vg_model.pt", it occurred this problem. Thank you in advance!

**Comment by he-dhamo** [comment]
Hello, first make sure you are using the correct configuration file for this checkpoint:
https://github.com/he-dhamo/simsg/blob/master/args_64_spade_vg.yaml

**Comment by wang-zm18** [comment]
I make sure I used the args_64_spade_vg.yaml.
![image](https://user-images.githubusercontent.com/47704679/147856131-6bf2c5e2-af34-4d68-865e-a48deeccedf8.png)

**Comment by wang-zm18** [comment]
When I load the chekpoints, I saw "decoder_net.decoder_modules.0.conv_0.bias", but "decoder_net.decoder_modules.0.conv_0.weight" is missing.

**Comment by he-dhamo** [comment]
For layer decoder_net.decoder_modules.0.conv_0 the checkpoint stores weight_orig, weight_u and weight_v, seemingly related to the spectral norm implementation. For me the loading works fine as the model expects these names. Is it possible that you are using a different pytorch or python version from our readme, that could cause the incompatibility?

**Comment by wang-zm18** [comment]
OK, thank you, I will have a try!
