### ISSUE TITLE
vocab.json

### ISSUE THREAD

**Issue by ganchaofan0000** [he-dhamo/simsg#14]
Could provide me the vocab.json file. I need it to transform the scene graph of other dataset to idx.

**Comment by azadef** [comment]
The preprocess_vg.py script should generate the vocab.json for the VG dataset, and for clever, it is already available as part of the dataset.

**Comment by ganchaofan0000** [comment]
> The preprocess_vg.py script should generate the vocab.json for the VG dataset, and for clever, it is already available as part of the dataset.

Thanks, I have generated it!
