### ISSUE TITLE
Resolution of output images.

### ISSUE THREAD

**Issue by 3288103265** [he-dhamo/simsg#4]
hi, dhamo,
     I have changed image size from 64\*64 to 128\*128 in args file, and its results were not bad. But when it comes to 256*256, cuda was out of memory. I want to know weather your framework is compatible to higher resolution? Of course, I should expore it by myself, but it is limited by my device  :)

**Comment by he-dhamo** [comment]
Hello, 
Given that the focus of our work was not high resolution (also limited by the GPU availability), we actually have not explored 256x256 resolution in our experiments.
