### ISSUE TITLE
Factorizable Net for CLEVR dataset

### ISSUE THREAD

**Issue by Zhongping-Zhang** [he-dhamo/simsg#9]
Hi,

Thank you for providing the code for this paper. I'm currently following up your work. 

I downloaded the CLEVR checkpoints (ckpts_clevr.zip) from "https://he-dhamo.github.io/SIMSG/#download", and got the similar quantitative results to Table 1. Since this repo doesn't include the code for Factorizable Net, does it mean the data loader of CLEVR directly load the prediction of Factorizable Net rather than the ground truth scene graph? Thanks again for your time!

**Comment by he-dhamo** [comment]
Hi there, for the CLEVR experiments we used ground truth graphs, as this is a toy dataset and the graphs are relatively simple.
